### ISSUE TITLE
bug: -force in destroy is not supported in TF v0.15

### ISSUE THREAD

**Issue by rodush** [jmccann/drone-terraform#127]
As mentioned in the docs https://www.terraform.io/upgrade-guides/0-15.html:

> The terraform destroy command no longer accepts the option -force. This was a previous name for the option in earlier Terraform versions, but we've since adopted -auto-approve for consistency with the terraform apply command.
>
> If you are using -force in an automated call to terraform destroy, change to using -auto-approve instead.

And currently 8:0.15 of the Plugin is broken in that sense, because of https://github.com/jmccann/drone-terraform/blob/master/plugin.go#L303

**Comment by jmccann** [comment]
fix merged and deployed with

```
jmccann/drone-terraform:8
jmccann/drone-terraform:8.2
jmccann/drone-terraform:8.2-0.15.1
```
