### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by josmo** [jmccann/drone-terraform#138]
@jmccann Just checking on the status of the plugin. Looks like there hasn't been a merge/release in a while. Totally down to fork or otherwise but wanted to check plans on it :)

**Comment by caioquirino** [comment]
Hi @josmo, AFAIK this project is being maintained normally. Please feel free to open issues or send PRs

**Comment by josmo** [comment]
Cool Cool, I just opened another PR with a newer  terraform version - would love to get some of the new features available, especially the move bocks :)
