### ISSUE TITLE
Cannot use git::ssh remote modules

### ISSUE THREAD

**Issue by shadowfax-chc** [jmccann/drone-terraform#42]
When using a module source with `git::ssh://`, the downloading of modules fails with:

```
[terraform-plan:L7:4s] Error loading Terraform: Error downloading modules: error downloading 'ssh://git@github.com/org/terraform-modules.git': /usr/bin/git exited with 128: Cloning into ''.terraform/modules' ....
[terraform-plan:L8:4s] ssh : line 1: ssh: not found
```

I assume this is because the docker image does not have ssh installed, but even if it did, there would need to be a way to provide credentials.

**Comment by msuterski** [comment]
How are you providing those credentials now? outside of the plugin

**Comment by shadowfax-chc** [comment]
I am not yet, since I havn't gotten past the lack of ssh yet. But I would expect to be able to provide the private key as a drone secret.

**Comment by ozbillwang** [comment]
@shadowfax-chc 

http://readme.drone.io/questions/how-to-clone-private-deps/

**Comment by combor** [comment]
I think this one fixed it: https://github.com/jmccann/drone-terraform/pull/69
