### ISSUE TITLE
feature required - block or pause step

### ISSUE THREAD

**Issue by ozbillwang** [jmccann/drone-terraform#51]
I'd like to run a dry-run command first, then I can check the log, if everything goes fine, then click a "unblock" button or confirm with y/n, then apply the change.

```
Step 1: terraform plan
step 2: block or pause, wait for confirmation
step 3: terraform apply
```

**Comment by jmccann** [comment]
I do exactly what @roobert mentioned.  I don't think you can pause and wait for manual confirmation with drone in general currently also.
