### ISSUE TITLE
Third party plugins

### ISSUE THREAD

**Issue by combor** [jmccann/drone-terraform#61]
Hi,
I'm trying to use ACME plugin with terraform but terraform fails with 
```
Error: provider.acme: fork/exec /root/.terraform.d/plugins/terraform-provider-acme: no such file or directory
```
To be sure that the file is there I have added:

```
		files, err := ioutil.ReadDir("/root/.terraform.d/plugins")
		if err != nil {
			log.Fatal(err)
		}

		for _, file := range files {
			fmt.Println("XXXXX")
			fmt.Println(file.Name())
		}
```
Just before https://github.com/jmccann/drone-terraform/blob/master/plugin.go#L103 and the output is:
```
terraform validate
XXXXX
terraform-provider-acme

Error: provider.acme: fork/exec /root/.terraform.d/plugins/terraform-provider-acme: no such file or directory
```
That's kinda odd. Have you seen such a thing in the past?

**Comment by combor** [comment]
Ok, I found the reason. https://github.com/vancluever/terraform-provider-acme/issues/29

Will close this for now.

**Comment by SriRohith** [comment]
Hi,
I got similar kind of issue while using terraform rest api provider, do you got any insight on this?

`terraform get
terraform validate

Error: provider.restapi: fork/exec /drone/src/terraform.d/plugins/linux_amd64/terraform-provider-restapi_v1.2.1-linux-amd64: no such file or directory`
