### ISSUE TITLE
multiple projects - single repository

### ISSUE THREAD

**Issue by roobert** [jmccann/drone-terraform#67]
Hi,

I've been trying to work out the best way to handle multiple terraform trees that exist in a single repository.

I can see two options:

1) create a drone config for the repo which includes a terraform block for every different terraform tree

pros:
  * parallel execution
  * easy to see which configs have passed/failed

cons:
  * with lots of projects this involves running 10s or 100s of tasks which can be really slow
  * all jobs have to run on every commit - no way to skip steps based on commit data

2) wrap terraform execution to iterate through a set of directories and run actions in each directory

pros:
  * simple enough to wrap terraform execution in a shell script which lists files changed in the last commit which means it's possible to only run terraform for configs which have changed 

cons:
  * serial execution

Given the trend in using single repositories as single source of truth these days I was wondering on your opinions on the best way to handle this use case, and whether support for this use case could possibly be added to this plugin if necessary (I'd be happy to work on any agreed implementation!).

Cheers,

**Comment by tonglil** [comment]
@roobert follow https://github.com/drone/drone/issues/1021 and what you want should be accomplish-able in 0.9.
