### ISSUE TITLE
Third Party Rest api plugin

### ISSUE THREAD

**Issue by SriRohith** [jmccann/drone-terraform#75]
Hi,
I'm getting this issue while using terraform rest api provider, do you got any insight on this?

```
terraform validate

Error: provider.restapi: fork/exec /drone/src/terraform.d/plugins/linux_amd64/terraform-provider-restapi_v1.2.1-linux-amd64: no such file or directory
```

**Comment by jmccann** [comment]
What version of the plugin are you using?  Do you have a snippet example of your pipeline?  Is that the full log output?

**Comment by jmccann** [comment]
Closing as stale
