### ISSUE TITLE
Terraform Version Error when running plan

### ISSUE THREAD

**Issue by wulfmann** [jmccann/drone-terraform#81]
I've been having trouble using this plugin, seemingly because the version of terraform that the container is using is too old compared to the version that generated my statefile.

Sample output:

```
Error:
Terraform doesn't allow running any operations against a state
that was written by a future Terraform version. The state is
reporting it is written by Terraform '0.11.11'
Please run at least that version of Terraform to continue.
```

Are you opposed to updating the version?

**Comment by jmccann** [comment]
It is possible to specify TF version to use outside of what is embedded into the image.  https://github.com/jmccann/drone-terraform/blob/master/DOCS.md

Also, you can build your own images based on this image with newer TF versions.
